dist: xenial
language: python
python: "3.7"
# command to install dependencies
install:
  - pip install "django>=2.1.7,<2.2" coveralls[yaml]
  - pip install .
# command to run tests
script:
  - coverage run `which django-admin` test --pythonpath . --settings tests.django.settings
after_success:
  - coveralls
